FROM  golang:1.21.0-alpine as builder

WORKDIR /project/capstone

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . .
RUN CGO_ENABLED=1 go build -tags tools,devtools -o /project/capstone/build/capstone-tools .

FROM alpine:latest

# to fix timezone not loaded
RUN apk add --no-cache tzdata

COPY --from=builder /project/capstone/build/capstone-tools /project/capstone/build/capstone-tools

WORKDIR /project/capstone/build/

ENTRYPOINT [ "sleep", "infinity" ]
