// Code generated by "go run myapp/tool/stringer -linecomment -type=CashierSessionStatus -output=cashier_session_enum_gen.go -swagoutput=../tool/swag/enum_gen/cashier_session_enum_gen.go -custom"; DO NOT EDIT.

package enum_gen

import (
	"github.com/go-openapi/spec"
)

func init() {
	PostSwaggerDefinitions["CashierSessionStatusEnum"] = spec.Schema{
		SchemaProps: spec.SchemaProps{
			Type: []string{"string"},
			Enum: []interface{}{
				"ACTIVE",
				"COMPLETED",
			},
		},
	}
}
