// Code generated by "go run myapp/tool/stringer -linecomment -type=DatabaseAction -output=database_action_enum_gen.go -swagoutput=../tool/swag/enum_gen/database_action_enum_gen.go -custom"; DO NOT EDIT.

package enum_gen

import (
	"github.com/go-openapi/spec"
)

func init() {
	PostSwaggerDefinitions["DatabaseActionEnum"] = spec.Schema{
		SchemaProps: spec.SchemaProps{
			Type: []string{"string"},
			Enum: []interface{}{
				"INSERT",
				"UPDATE",
				"DELETE",
			},
		},
	}
}
