// Code generated by "go run myapp/tool/stringer -linecomment -type=DeliveryOrderReviewType -output=delivery_order_review_enum_gen.go -swagoutput=../tool/swag/enum_gen/delivery_order_review_enum_gen.go -custom"; DO NOT EDIT.

package enum_gen

import (
	"github.com/go-openapi/spec"
)

func init() {
	PostSwaggerDefinitions["DeliveryOrderReviewTypeEnum"] = spec.Schema{
		SchemaProps: spec.SchemaProps{
			Type: []string{"string"},
			Enum: []interface{}{
				"PRODUCT",
				"DELIVERY",
			},
		},
	}
}
