// Code generated by "go run myapp/tool/stringer -linecomment -type=PermissionType -output=permission_type_enum_gen.go -swagoutput=../tool/swag/enum_gen/permission_type_enum_gen.go -custom"; DO NOT EDIT.

package enum_gen

import (
	"github.com/go-openapi/spec"
)

func init() {
	PostSwaggerDefinitions["PermissionTypeEnum"] = spec.Schema{
		SchemaProps: spec.SchemaProps{
			Type: []string{"string"},
			Enum: []interface{}{
				"ADMIN",
				"GLOBAL",
				"MUST_ASSIGN",
				"MUST_ON_SITE",
				"MUST_ASSIGN_AND_ON_SITE",
				"MUST_ASSIGN_AND_ON_SITE_STRICT",
			},
		},
	}
}
