// Code generated by "go run myapp/tool/stringer -linecomment -type=PurchaseOrderStatus -output=purchase_order_enum_gen.go -swagoutput=../tool/swag/enum_gen/purchase_order_enum_gen.go -custom"; DO NOT EDIT.

package enum_gen

import (
	"github.com/go-openapi/spec"
)

func init() {
	PostSwaggerDefinitions["PurchaseOrderStatusEnum"] = spec.Schema{
		SchemaProps: spec.SchemaProps{
			Type: []string{"string"},
			Enum: []interface{}{
				"PENDING",
				"ONGOING",
				"CANCELED",
				"COMPLETED",
			},
		},
	}
}
