// Code generated by "go run myapp/tool/stringer -linecomment -type=RoleType -output=role_type_enum_gen.go -swagoutput=../tool/swag/enum_gen/role_type_enum_gen.go -custom"; DO NOT EDIT.

package enum_gen

import (
	"github.com/go-openapi/spec"
)

func init() {
	PostSwaggerDefinitions["RoleTypeEnum"] = spec.Schema{
		SchemaProps: spec.SchemaProps{
			Type: []string{"string"},
			Enum: []interface{}{
				"SUPER_ADMIN",
				"GLOBAL",
				"ADMIN",
			},
		},
	}
}
