// Code generated by "go run myapp/tool/stringer -linecomment -type=TiktokProductStatus,TiktokProductDimensionUnit,TiktokProductPackageWeight -output=tiktok_product_enum_gen.go -swagoutput=../tool/swag/enum_gen/tiktok_product_enum_gen.go -custom"; DO NOT EDIT.

package enum_gen

import (
	"github.com/go-openapi/spec"
)

func init() {
	PostSwaggerDefinitions["TiktokProductStatusEnum"] = spec.Schema{
		SchemaProps: spec.SchemaProps{
			Type: []string{"string"},
			Enum: []interface{}{
				"ACTIVE",
				"IN_ACTIVE",
			},
		},
	}

	PostSwaggerDefinitions["TiktokProductDimensionUnitEnum"] = spec.Schema{
		SchemaProps: spec.SchemaProps{
			Type: []string{"string"},
			Enum: []interface{}{
				"CENTIMETER",
			},
		},
	}

	PostSwaggerDefinitions["TiktokProductPackageWeightEnum"] = spec.Schema{
		SchemaProps: spec.SchemaProps{
			Type: []string{"string"},
			Enum: []interface{}{
				"KILOGRAM",
			},
		},
	}
}
