// Code generated by "go run myapp/tool/stringer -linecomment -type=WebhookTiktokOrderStatusChange -output=webhook_enum_gen.go -swagoutput=../tool/swag/enum_gen/webhook_enum_gen.go -custom"; DO NOT EDIT.

package enum_gen

import (
	"github.com/go-openapi/spec"
)

func init() {
	PostSwaggerDefinitions["WebhookTiktokOrderStatusChangeEnum"] = spec.Schema{
		SchemaProps: spec.SchemaProps{
			Type: []string{"string"},
			Enum: []interface{}{
				"UNPAID",
				"ON_HOLD",
				"AWAITING_SHIPMENT",
				"AWAITING_COLLECTION",
				"CANCEL",
				"IN_TRANSIT",
				"DELIVERED",
				"COMPLETED",
			},
		},
	}
}
