// Code generated by "go run myapp/tool/stringer -linecomment -type=DebtStatus,DebtSource -output=debt_enum_gen.go -swagoutput=../tool/swag/enum_gen/debt_enum_gen.go -custom"; DO NOT EDIT.

package data_type

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DebtStatusUnpaid-1]
	_ = x[DebtStatusHalfPaid-2]
	_ = x[DebtStatusCanceled-3]
	_ = x[DebtStatusPaid-4]
	_ = x[DebtStatusReturned-5]
}

const _DebtStatus_nameReadable = "UNPAID, HALF_PAID, CANCELED, PAID, RETURNED"

const _DebtStatus_name = "UNPAIDHALF_PAIDCANCELEDPAIDRETURNED"

var _DebtStatus_index = [...]uint8{0, 6, 15, 23, 27, 35}

func (i *DebtStatus) Determine(s string) {
	switch s {
	case "UNPAID":
		*i = DebtStatusUnpaid
	case "HALF_PAID":
		*i = DebtStatusHalfPaid
	case "CANCELED":
		*i = DebtStatusCanceled
	case "PAID":
		*i = DebtStatusPaid
	case "RETURNED":
		*i = DebtStatusReturned
	default:
		*i = 0
	}
}

func (i DebtStatus) IsValid() bool {
	if i == 0 {
		return false
	}

	return true
}

func (i DebtStatus) GetValidValuesString() string {
	return _DebtStatus_nameReadable
}

func (i DebtStatus) String() string {
	i -= 1
	if i < 0 || i >= DebtStatus(len(_DebtStatus_index)-1) {
		return "DebtStatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}

	return _DebtStatus_name[_DebtStatus_index[i]:_DebtStatus_index[i+1]]
}

func (i DebtStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *DebtStatus) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}

	i.Determine(s)

	return nil
}

func (i *DebtStatus) UnmarshalText(b []byte) error {
	i.Determine(string(b))

	return nil
}

func (i *DebtStatus) Scan(value interface{}) error {
	switch s := value.(type) {
	case string:
		i.Determine(s)
	default:
		return fmt.Errorf("unsupported Scan, storing driver.Value type %T into type %T", value, i)
	}

	return nil
}

func (i DebtStatus) Value() (driver.Value, error) {
	return i.String(), nil
}

func DebtStatusP(v DebtStatus) *DebtStatus {
	return &v
}

func ListDebtStatus() []DebtStatus {
	return []DebtStatus{
		DebtStatusUnpaid,
		DebtStatusHalfPaid,
		DebtStatusCanceled,
		DebtStatusPaid,
		DebtStatusReturned,
	}
}

func ListDebtStatusString() []string {
	return []string{
		DebtStatusUnpaid.String(),
		DebtStatusHalfPaid.String(),
		DebtStatusCanceled.String(),
		DebtStatusPaid.String(),
		DebtStatusReturned.String(),
	}
}

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DebtSourceProductReceive-1]
}

const _DebtSource_nameReadable = "PRODUCT_RECEIVE"

const _DebtSource_name = "PRODUCT_RECEIVE"

var _DebtSource_index = [...]uint8{0, 15}

func (i *DebtSource) Determine(s string) {
	switch s {
	case "PRODUCT_RECEIVE":
		*i = DebtSourceProductReceive
	default:
		*i = 0
	}
}

func (i DebtSource) IsValid() bool {
	if i == 0 {
		return false
	}

	return true
}

func (i DebtSource) GetValidValuesString() string {
	return _DebtSource_nameReadable
}

func (i DebtSource) String() string {
	i -= 1
	if i < 0 || i >= DebtSource(len(_DebtSource_index)-1) {
		return "DebtSource(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}

	return _DebtSource_name[_DebtSource_index[i]:_DebtSource_index[i+1]]
}

func (i DebtSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *DebtSource) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}

	i.Determine(s)

	return nil
}

func (i *DebtSource) UnmarshalText(b []byte) error {
	i.Determine(string(b))

	return nil
}

func (i *DebtSource) Scan(value interface{}) error {
	switch s := value.(type) {
	case string:
		i.Determine(s)
	default:
		return fmt.Errorf("unsupported Scan, storing driver.Value type %T into type %T", value, i)
	}

	return nil
}

func (i DebtSource) Value() (driver.Value, error) {
	return i.String(), nil
}

func DebtSourceP(v DebtSource) *DebtSource {
	return &v
}

func ListDebtSource() []DebtSource {
	return []DebtSource{
		DebtSourceProductReceive,
	}
}

func ListDebtSourceString() []string {
	return []string{
		DebtSourceProductReceive.String(),
	}
}
