// Code generated by "go run myapp/tool/stringer -linecomment -type=DeliveryOrderStatus -output=delivery_order_enum_gen.go -swagoutput=../tool/swag/enum_gen/delivery_order_enum_gen.go -custom"; DO NOT EDIT.

package data_type

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DeliveryOrderStatusPending-1]
	_ = x[DeliveryOrderStatusCompleted-2]
}

const _DeliveryOrderStatus_nameReadable = "PENDING, COMPLETED"

const _DeliveryOrderStatus_name = "PENDINGCOMPLETED"

var _DeliveryOrderStatus_index = [...]uint8{0, 7, 16}

func (i *DeliveryOrderStatus) determine(s string) {
	switch s {
	case "PENDING":
		*i = DeliveryOrderStatusPending
	case "COMPLETED":
		*i = DeliveryOrderStatusCompleted
	default:
		*i = 0
	}
}

func (i DeliveryOrderStatus) IsValid() bool {
	if i == 0 {
		return false
	}

	return true
}

func (i DeliveryOrderStatus) GetValidValuesString() string {
	return _DeliveryOrderStatus_nameReadable
}

func (i DeliveryOrderStatus) String() string {
	i -= 1
	if i < 0 || i >= DeliveryOrderStatus(len(_DeliveryOrderStatus_index)-1) {
		return "DeliveryOrderStatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}

	return _DeliveryOrderStatus_name[_DeliveryOrderStatus_index[i]:_DeliveryOrderStatus_index[i+1]]
}

func (i DeliveryOrderStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *DeliveryOrderStatus) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}

	i.determine(s)

	return nil
}

func (i *DeliveryOrderStatus) UnmarshalText(b []byte) error {
	i.determine(string(b))

	return nil
}

func (i *DeliveryOrderStatus) Scan(value interface{}) error {
	switch s := value.(type) {
	case string:
		i.determine(s)
	default:
		return fmt.Errorf("unsupported Scan, storing driver.Value type %T into type %T", value, i)
	}

	return nil
}

func (i DeliveryOrderStatus) Value() (driver.Value, error) {
	return i.String(), nil
}

func DeliveryOrderStatusP(v DeliveryOrderStatus) *DeliveryOrderStatus {
	return &v
}

func ListDeliveryOrderStatus() []DeliveryOrderStatus {
	return []DeliveryOrderStatus{
		DeliveryOrderStatusPending,
		DeliveryOrderStatusCompleted,
	}
}

func ListDeliveryOrderStatusString() []string {
	return []string{
		DeliveryOrderStatusPending.String(),
		DeliveryOrderStatusCompleted.String(),
	}
}
