// Code generated by "go run myapp/tool/stringer -linecomment -type=ProductReturnStatus -output=product_return_enum_gen.go -swagoutput=../tool/swag/enum_gen/product_return_enum_gen.go -custom"; DO NOT EDIT.

package data_type

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProductReturnStatusPending-1]
	_ = x[ProductReturnStatusCompleted-2]
}

const _ProductReturnStatus_nameReadable = "PENDING, COMPLETED"

const _ProductReturnStatus_name = "PENDINGCOMPLETED"

var _ProductReturnStatus_index = [...]uint8{0, 7, 16}

func (i *ProductReturnStatus) Determine(s string) {
	switch s {
	case "PENDING":
		*i = ProductReturnStatusPending
	case "COMPLETED":
		*i = ProductReturnStatusCompleted
	default:
		*i = 0
	}
}

func (i ProductReturnStatus) IsValid() bool {
	if i == 0 {
		return false
	}

	return true
}

func (i ProductReturnStatus) GetValidValuesString() string {
	return _ProductReturnStatus_nameReadable
}

func (i ProductReturnStatus) String() string {
	i -= 1
	if i < 0 || i >= ProductReturnStatus(len(_ProductReturnStatus_index)-1) {
		return "ProductReturnStatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}

	return _ProductReturnStatus_name[_ProductReturnStatus_index[i]:_ProductReturnStatus_index[i+1]]
}

func (i ProductReturnStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *ProductReturnStatus) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}

	i.Determine(s)

	return nil
}

func (i *ProductReturnStatus) UnmarshalText(b []byte) error {
	i.Determine(string(b))

	return nil
}

func (i *ProductReturnStatus) Scan(value interface{}) error {
	switch s := value.(type) {
	case string:
		i.Determine(s)
	default:
		return fmt.Errorf("unsupported Scan, storing driver.Value type %T into type %T", value, i)
	}

	return nil
}

func (i ProductReturnStatus) Value() (driver.Value, error) {
	return i.String(), nil
}

func ProductReturnStatusP(v ProductReturnStatus) *ProductReturnStatus {
	return &v
}

func ListProductReturnStatus() []ProductReturnStatus {
	return []ProductReturnStatus{
		ProductReturnStatusPending,
		ProductReturnStatusCompleted,
	}
}

func ListProductReturnStatusString() []string {
	return []string{
		ProductReturnStatusPending.String(),
		ProductReturnStatusCompleted.String(),
	}
}
