// Code generated by "go run myapp/tool/stringer -linecomment -type=Role -output=role_enum_gen.go -swagoutput=../tool/swag/enum_gen/role_enum_gen.go -custom"; DO NOT EDIT.

package data_type

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RoleSuperAdmin-1]
	_ = x[RoleClusterManager-2]
	_ = x[RoleClinicManager-3]
	_ = x[RoleDoctor-4]
	_ = x[RoleNurse-5]
	_ = x[RoleCashier-6]
	_ = x[RolePharmacist-7]
	_ = x[RoleOperationManager-8]
	_ = x[RolePharmacyManager-9]
	_ = x[RoleFinanceManager-10]
	_ = x[RoleAssistantClinicManager-11]
}

const _Role_nameReadable = "Super Admin, Cluster Manager, Clinic Manager, Doctor, Nurse, Cashier, Pharmacist, Operation Manager, Pharmacy Manager, Finance Manager, Assistant Clinic Manager"

const _Role_name = "Super AdminCluster ManagerClinic ManagerDoctorNurseCashierPharmacistOperation ManagerPharmacy ManagerFinance ManagerAssistant Clinic Manager"

var _Role_index = [...]uint8{0, 11, 26, 40, 46, 51, 58, 68, 85, 101, 116, 140}

func (i *Role) determine(s string) {
	switch s {
	case "Super Admin":
		*i = RoleSuperAdmin
	case "Cluster Manager":
		*i = RoleClusterManager
	case "Clinic Manager":
		*i = RoleClinicManager
	case "Doctor":
		*i = RoleDoctor
	case "Nurse":
		*i = RoleNurse
	case "Cashier":
		*i = RoleCashier
	case "Pharmacist":
		*i = RolePharmacist
	case "Operation Manager":
		*i = RoleOperationManager
	case "Pharmacy Manager":
		*i = RolePharmacyManager
	case "Finance Manager":
		*i = RoleFinanceManager
	case "Assistant Clinic Manager":
		*i = RoleAssistantClinicManager
	default:
		*i = 0
	}
}

func (i Role) IsValid() bool {
	if i == 0 {
		return false
	}

	return true
}

func (i Role) GetValidValuesString() string {
	return _Role_nameReadable
}

func (i Role) String() string {
	i -= 1
	if i < 0 || i >= Role(len(_Role_index)-1) {
		return "Role(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}

	return _Role_name[_Role_index[i]:_Role_index[i+1]]
}

func (i Role) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *Role) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}

	i.determine(s)

	return nil
}

func (i *Role) UnmarshalText(b []byte) error {
	i.determine(string(b))

	return nil
}

func (i *Role) Scan(value interface{}) error {
	switch s := value.(type) {
	case string:
		i.determine(s)
	default:
		return fmt.Errorf("unsupported Scan, storing driver.Value type %T into type %T", value, i)
	}

	return nil
}

func (i Role) Value() (driver.Value, error) {
	return i.String(), nil
}

func RoleP(v Role) *Role {
	return &v
}

func ListRole() []Role {
	return []Role{
		RoleSuperAdmin,
		RoleClusterManager,
		RoleClinicManager,
		RoleDoctor,
		RoleNurse,
		RoleCashier,
		RolePharmacist,
		RoleOperationManager,
		RolePharmacyManager,
		RoleFinanceManager,
		RoleAssistantClinicManager,
	}
}

func ListRoleString() []string {
	return []string{
		RoleSuperAdmin.String(),
		RoleClusterManager.String(),
		RoleClinicManager.String(),
		RoleDoctor.String(),
		RoleNurse.String(),
		RoleCashier.String(),
		RolePharmacist.String(),
		RoleOperationManager.String(),
		RolePharmacyManager.String(),
		RoleFinanceManager.String(),
		RoleAssistantClinicManager.String(),
	}
}
